---
- hosts: all
  connection: local
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      use_proxy: no
      use_ssl: yes
      validate_certs: no
  tasks:
    - name: Add a new contract to EPG binding
      aci_epg_to_contract:
        <<: *aci_login
        tenant: '{{tenant_name}}'
        ap: '{{ap_name}}'
        epg: '{{epg1_name}}'
        contract: "{{ CtName  }}"
        contract_type: consumer
        state: present

    - name: Add a new contract to EPG binding
      aci_epg_to_contract:
        <<: *aci_login
        tenant: '{{tenant_name}}'
        ap: '{{ap_name}}'
        epg: '{{epg2_name}}'
        contract: "{{ CtName  }}"
        contract_type: provider
        state: present
