---
- hosts: all
  connection: local
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      use_proxy: no
      use_ssl: yes
      validate_certs: no
  tasks:
  - name: Add a new contract
    aci_contract:
      <<: *aci_login
      tenant: "{{ Tenant }}"
      contract: "{{ CtName  }}"
      scope: "{{ CtScope  }}"
      state: present
      validate_certs: no

  - name: Add a new contract subject
    aci_contract_subject:
      <<: *aci_login
      tenant: "{{ Tenant }}"
      contract: "{{ CtName  }}"
      subject: "{{ CtSubject  }}"
      reverse_filter: yes
