---
- hosts: all
  connection: local
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      use_proxy: no
      use_ssl: yes
      validate_certs: no
  tasks:
  - name: Add a new contract
    aci_contract:
      tenant: "{{ Tenant }}"
      contract: "{{ CtName  }}"
      scope: "{{ CtScope  }}"
      state: present
      validate_certs: no

  - name: Add a new contract subject
    aci_contract_subject:
      tenant: "{{ Tenant }}"
      contract: "{{ CtName  }}"
      subject: "{{ CtSubject  }}"
      reverse_filter: yes

  - name: Add a new filter to a tenant
    aci_filter:
      filter: "{{ web_filter }}"
      tenant: "{{ Tenant }}"
      state: present
      validate_certs: no

  - aci_filter_entry:
      state: present
      validate_certs: no
      entry: "{{ entry }}"
      tenant: "{{ Tenant }}"
      ether_type: "{{  ether_type }}"
      ip_protocol: "{{ ip_proto }}"
      dst_port: "{{ destination_port }}"
      filter: "{{ web_filter }}"

  - name: Add a new contract subject to filter binding
    aci_contract_subject_to_filter:
      tenant: "{{ Tenant }}"
      contract: "{{ CtName  }}"
      subject: "{{ CtSubject  }}"
      filter: "{{ web_filter }}"
      state: present
      validate_certs: no
