---
- hosts: all
  connection: local
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      use_proxy: no
      use_ssl: yes
      validate_certs: no
  tasks:
  - name: Add a tenant using aci_tenant
    aci_tenant:
      <<: *aci_login
      tenant: '{{awx_tenant_name}}'
      description: 'created by Ansible Tower'
      state: '{{awx_tenant_state}}'
